[[FastTransforms]]
arch = "aarch64"
git-tree-sha1 = "4525fe895b4a01995c9597a82245085d83a50eb9"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "57e069a0bc38311d72be9e24f750bfa86f7b30b5d58bae265fd393459440c587"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.0+0/FastTransforms.v0.5.0.aarch64-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "aarch64"
git-tree-sha1 = "bb2c43a42e515e0942409013857cb2a63477675e"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "eb31125fa4e5fc53255c5502b469509cd39a13b330b93e5a774d692b0de7ad21"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.0+0/FastTransforms.v0.5.0.aarch64-linux-musl.tar.gz"
[[FastTransforms]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "eeb243fbf4a2ace411636d82b91d9a9a683a8f8f"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "54f934d97f2a8e85f95ed093196f787e78582f72a0f64cd05fbd69b0d9da7b99"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.0+0/FastTransforms.v0.5.0.armv7l-linux-gnueabihf.tar.gz"
[[FastTransforms]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "04584fb9736cd226708e3b2e74e844a7ec9c98ce"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "5d412fae194c4d4628a10c66bdfa1dfe20eaf6b3e49c34f972f6fbe26a2879f7"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.0+0/FastTransforms.v0.5.0.armv7l-linux-musleabihf.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "0f2a3b8d4cf1f0776de6cfa727854a0c7effca39"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "e2359ffa106d4a692b189c6991b4b1613fad6e0f855c9fa786b4dc12cc970c3e"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.0+0/FastTransforms.v0.5.0.i686-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "8da16a13b6cd36ad2473dfb2837baf513246739c"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "e0aea2c25bdeb9786460ca7a1c98a4858868eb72e9e867b1e42e877d7479bd8c"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.0+0/FastTransforms.v0.5.0.i686-linux-musl.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "49c6da78567a1d96d6ea19aeb70212dfac5ff59f"
os = "windows"

    [[FastTransforms.download]]
    sha256 = "0958da42bcb9e0b71bc9f99b793bcadddebc421f53fd9e5193507ad2b60fca3c"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.0+0/FastTransforms.v0.5.0.i686-w64-mingw32.tar.gz"
[[FastTransforms]]
arch = "powerpc64le"
git-tree-sha1 = "193efacb11a712d06b77d51a586d6976edb17203"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "fcc9a276b7ad24ae40e8870d61b9bfb7dbc02d224e8d48ba056b41948ed23ba3"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.0+0/FastTransforms.v0.5.0.powerpc64le-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "df2e8174e6accfb338b68ef8c06aabf6f2a35a36"
os = "macos"

    [[FastTransforms.download]]
    sha256 = "dcc3e2ae48e45ae37b82ab6da27b352e3ee77910eac788196dc7c45acd73645d"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.0+0/FastTransforms.v0.5.0.x86_64-apple-darwin.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "4e827e656d0f870b11b0d6def5d68b97589a3b60"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "8d7bfd85852afb9b5b9eb9375850b188a65a4235256908d6a5fe5b50a39163e7"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.0+0/FastTransforms.v0.5.0.x86_64-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "f69859d02e90398a124e484b1f5676a3f32788dd"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "6246eb252f91ab65ce207dd9a3f30c969ec4fedce753d872ad0a78fd4fc03223"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.0+0/FastTransforms.v0.5.0.x86_64-linux-musl.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "a5efdeebc7db9beaf7de3accc1d1f402d2ea152b"
os = "freebsd"

    [[FastTransforms.download]]
    sha256 = "98ab870556824e4365761af4a3537797b1da94608e2af3e78a51e5d3a8f97834"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.0+0/FastTransforms.v0.5.0.x86_64-unknown-freebsd.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "19413b1bddb57428b745aa8ecb13bbb52801b582"
os = "windows"

    [[FastTransforms.download]]
    sha256 = "5ce37c70c2f5db0f46f2120c5c2270e54bcfc74a82d1089f46d9de5082e626db"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.0+0/FastTransforms.v0.5.0.x86_64-w64-mingw32.tar.gz"
