[[FastTransforms]]
arch = "aarch64"
git-tree-sha1 = "c3b88b4d52d0e0dce49fefb0302b55bd02c8a17c"
os = "macos"

    [[FastTransforms.download]]
    sha256 = "d4264bbd93bcb4b3e15acd09a812f5fc54a8409e02d05bfefbf190c52861be37"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.3+0/FastTransforms.v0.5.3.aarch64-apple-darwin.tar.gz"
[[FastTransforms]]
arch = "aarch64"
git-tree-sha1 = "42b7c057465444519699c7761ee6a5dcbf6a93b0"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "e9a569c8778019ee62538d0cf762c4aaae11b847fb660d1e2d5cb4545a77b6cc"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.3+0/FastTransforms.v0.5.3.aarch64-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "aarch64"
git-tree-sha1 = "15e61863debf4762cbce05a98e42a844848c1110"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "8777b349761a4378e2f08f552e128f7052d5159fdb65b7b5517149076a33d4ce"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.3+0/FastTransforms.v0.5.3.aarch64-linux-musl.tar.gz"
[[FastTransforms]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "eda447cbc514d84a357026e206f6a1a2774457d5"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "a0692d1a7be5b132b19a6369241e6dfac7e05fd6caccafeaa561d964cbe138d9"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.3+0/FastTransforms.v0.5.3.armv6l-linux-gnueabihf.tar.gz"
[[FastTransforms]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "43d2af5cec90ea3014767524ca19d7390e0306e1"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "e90120b088708ebe81a55e93c82551d841b93e709f96e3aa5e7b570c007739a6"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.3+0/FastTransforms.v0.5.3.armv6l-linux-musleabihf.tar.gz"
[[FastTransforms]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "379501e5005cd71ed09e7bac2753779f494fd352"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "e351504b4e2d7b0fa05d4adc39f61a706d9a7a205f9f85f2990277e963d95b9f"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.3+0/FastTransforms.v0.5.3.armv7l-linux-gnueabihf.tar.gz"
[[FastTransforms]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "09dcd2d0532a5e720cf5d32fbb1a395d733b0515"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "4e40fdf74f27fa92a0d0a01f2dcf7c356e57374427751b3ded52cf46fecb7ab7"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.3+0/FastTransforms.v0.5.3.armv7l-linux-musleabihf.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "77b07c3af2118e03842f65658ce1861e82283f10"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "ea519b92c0e5d61e9fdb9bf556129699be8b131284c0a57d7467d9a17b4b1783"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.3+0/FastTransforms.v0.5.3.i686-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "2932604069488367d68ca678dffba2d5adc25ff2"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "2b91e312fd02eccc670bf54f993b633c0b9df30faf3d642c318328f0fa63ff75"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.3+0/FastTransforms.v0.5.3.i686-linux-musl.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "bb5d5048c3574e3ac76b3fc7104bef9a1ba2a261"
os = "windows"

    [[FastTransforms.download]]
    sha256 = "5142072439fbc5ac73c84d53bc1179e43a96cad2b57199f42752063985c02873"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.3+0/FastTransforms.v0.5.3.i686-w64-mingw32.tar.gz"
[[FastTransforms]]
arch = "powerpc64le"
git-tree-sha1 = "c7a0a06d5456ba068952a3e2f1ce23cb38cd262e"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "1c2ac2f9fe3158af3c6487bc210c67b2f4e3e01920202553d03828628f045ba1"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.3+0/FastTransforms.v0.5.3.powerpc64le-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "e8d61b743453153fa7c853bbf11857d76f080c8a"
os = "macos"

    [[FastTransforms.download]]
    sha256 = "0a9486510ef2f4b3469b9202f709a4ae457c240b5f43d0692318da683292ada1"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.3+0/FastTransforms.v0.5.3.x86_64-apple-darwin.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "9afa40ec8f425b282469dced930ce8abb0eae7cd"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "001bb4632450a8eca665774cf555672054b8d07bc3c7c99b68da6704fa7d1cdf"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.3+0/FastTransforms.v0.5.3.x86_64-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "82c787adafc1149c5af88221b75f3e35a18eb246"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "5091c8339040b27f9da2abc98779bc433c2cc06037be81583ca20e46caa789bd"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.3+0/FastTransforms.v0.5.3.x86_64-linux-musl.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "9bb2232f967117eca0ee2bfc4e2556a80bc49c13"
os = "freebsd"

    [[FastTransforms.download]]
    sha256 = "edce5e73277cf0f2e5227911044bb3735f10265a8cbd88ff3cf1a04f42600e45"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.3+0/FastTransforms.v0.5.3.x86_64-unknown-freebsd.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "19285336694fffeb95ab5073db9373c515e58a69"
os = "windows"

    [[FastTransforms.download]]
    sha256 = "8441d4010940dab4ee750bc1ef16dcad65bc4dce3f7ca9a740c1596a523df97e"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.3+0/FastTransforms.v0.5.3.x86_64-w64-mingw32.tar.gz"
