[[FastTransforms]]
arch = "aarch64"
git-tree-sha1 = "62b9f023b0cbe33dd2ae8fd0a2230bcfb5ce0a5b"
os = "macos"

    [[FastTransforms.download]]
    sha256 = "460a3ab8a257554894d7e3bb1971d29556eff316cb948420e082f26477695ad0"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.3+0/FastTransforms.v0.6.3.aarch64-apple-darwin.tar.gz"
[[FastTransforms]]
arch = "aarch64"
git-tree-sha1 = "ffa9cb40e6ab0c68c86781bde81b10e4ee261b49"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "c80bde66474ab361e1c01ecc398800c22ee0262e3d123b4b0b79c675df4cff82"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.3+0/FastTransforms.v0.6.3.aarch64-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "aarch64"
git-tree-sha1 = "d9e1511ec7f47cabfbf74d753df4f95bee0a7e51"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "a692938dd3ff88447aeb6bb97a6d5bb9d9891015d408c72bacc03c695313ea4e"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.3+0/FastTransforms.v0.6.3.aarch64-linux-musl.tar.gz"
[[FastTransforms]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d8d7615202e1b7b4d5af16d60c6ab5040463301a"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "228ed0068102ee2b7e67cb84ca970e53ea090a1bb17bf59f6c30f08efc7e0128"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.3+0/FastTransforms.v0.6.3.armv6l-linux-gnueabihf.tar.gz"
[[FastTransforms]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2042656ba67a2bf9077aa3c868e9111a86710c38"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "7508b6cdaec73d4d3a7d4871eb534ddc0c685806c2ef99d4b5cc8bb27b9cf049"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.3+0/FastTransforms.v0.6.3.armv6l-linux-musleabihf.tar.gz"
[[FastTransforms]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b1c72e11f7e325b9dd10f5cd1d42299961139890"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "f7971b75663c8fbbf7db6432b2a352183cae0e3e681b079fea0a26aa4400752d"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.3+0/FastTransforms.v0.6.3.armv7l-linux-gnueabihf.tar.gz"
[[FastTransforms]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "31c796037cd40a01c8eb91f90c2284c7695d051c"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "302b1f18118a5f823638434304ed7af111138f4bbe0acff5535eed23da295b6a"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.3+0/FastTransforms.v0.6.3.armv7l-linux-musleabihf.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "622cc240ae28294dbbe318cc0f77b084b3d63227"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "f3fcbbc4c800cda77ca933131f0b51c50070bcd2c2455879269be2421d03c89d"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.3+0/FastTransforms.v0.6.3.i686-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "13dba3f7ee621fc270450df16d089704a4328756"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "b62ad5605e4bb9196b9e427e731998f6bebd8a4480cdebd4a99b3380a38d83ca"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.3+0/FastTransforms.v0.6.3.i686-linux-musl.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "ed3727522f902e13c4deca5b98082093177b9b98"
os = "windows"

    [[FastTransforms.download]]
    sha256 = "c6e3f75825bebefc72d52e3a88e45a3f8e9193eea0327b20689f5ac2d98f0883"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.3+0/FastTransforms.v0.6.3.i686-w64-mingw32.tar.gz"
[[FastTransforms]]
arch = "powerpc64le"
git-tree-sha1 = "23b640146cb8d01aa7ec16963857c5d91e1c1d85"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "d5940d09992feb73516ff0b0241e487578bfe5cd579e0ff2507930ce29b51d20"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.3+0/FastTransforms.v0.6.3.powerpc64le-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "099e42260ef94dbbf653088946baf2d5fa487c5c"
os = "macos"

    [[FastTransforms.download]]
    sha256 = "f7ebd7a5abeb2ce47f9116640017f8f6a635f5558145dc79ebf89956da500735"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.3+0/FastTransforms.v0.6.3.x86_64-apple-darwin.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "94bf85eb783cd1d11745eb607644cc2873d858fe"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "18db424dba15844d42fe03a733794732eb081729e676a2784fcdc03783b228a5"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.3+0/FastTransforms.v0.6.3.x86_64-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "e5cf751b424b8332e1811fdc335fdbd86ebc0578"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "b520874e01c0ad6c14075f37c9ca5c3174bf2d6c7030256e51bc90a516148fc1"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.3+0/FastTransforms.v0.6.3.x86_64-linux-musl.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "aa7ab443d32ee5e4aacec702d8e354ab37a17d05"
os = "freebsd"

    [[FastTransforms.download]]
    sha256 = "ae03bd7d2c2df2171efdac892e619fc9633d91f3832adde9248b048afd05d1ae"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.3+0/FastTransforms.v0.6.3.x86_64-unknown-freebsd.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "a4d2e6bb28c9157c1c9ce600fafb36270a6fde9f"
os = "windows"

    [[FastTransforms.download]]
    sha256 = "b9f04b79587d1627e80a4c389c0b687ff66fde568e6d94bd6a4c3a007cc00bbb"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.3+0/FastTransforms.v0.6.3.x86_64-w64-mingw32.tar.gz"
