[[FastTransforms]]
arch = "aarch64"
git-tree-sha1 = "adcf44cd4333a4f75afb1b5826eaf27daeb018a8"
os = "macos"

    [[FastTransforms.download]]
    sha256 = "b560107904f5c7760c6c0a8e32054becbeab1e633791f2bd81f9a71d23d3667e"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.4+0/FastTransforms.v0.6.4.aarch64-apple-darwin.tar.gz"
[[FastTransforms]]
arch = "aarch64"
git-tree-sha1 = "efc8cdbe952a165fb2a1fc3e4215e1f17a9da96d"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "ffcc61227a44778b70b0ce1e8c7e826feaa5d20172e247ba83c2a4aa86a34327"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.4+0/FastTransforms.v0.6.4.aarch64-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "aarch64"
git-tree-sha1 = "b01cb700f3745f3e4ce866ba7665a70141e05832"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "af8ac11ac878aeac270f847690fb90819c0dcd80e818c3022292c9b9a69135e3"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.4+0/FastTransforms.v0.6.4.aarch64-linux-musl.tar.gz"
[[FastTransforms]]
arch = "aarch64"
git-tree-sha1 = "e467b8c9b3f75bae1b53287d24530b71b53cee8d"
os = "freebsd"

    [[FastTransforms.download]]
    sha256 = "8a6724b10dfe81d6ae86feac684b7603fb20e3db80354b6d00c652365879ec50"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.4+0/FastTransforms.v0.6.4.aarch64-unknown-freebsd.tar.gz"
[[FastTransforms]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4309b5acbfc62d324d756c236f91a43f883a05f9"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "ea87b506ee61e695b34b35473b5ade5cb424bc031a179d99fd5bc6f86a0c5fc9"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.4+0/FastTransforms.v0.6.4.armv6l-linux-gnueabihf.tar.gz"
[[FastTransforms]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d934f3772346e9c3f4035b577d0890c6bdf58dd3"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "80098fa10f8efb9da99698f913aac66c3786b0def00be377a63d6ed367974814"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.4+0/FastTransforms.v0.6.4.armv6l-linux-musleabihf.tar.gz"
[[FastTransforms]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7cbd8a096c3c3582c5f046bc9deeba755ae9a1f1"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "4d8c0636d1ea687b4fc338112e6d553b28e1ac87dd789ed88e951a08728d1db3"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.4+0/FastTransforms.v0.6.4.armv7l-linux-gnueabihf.tar.gz"
[[FastTransforms]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fbdcbd246652dc42e2acae85b2c5bafb6d2f67b0"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "14b632f8f4134939796c66ba95aa3227a4f877a8fbfea36d8f28e004a7e083ae"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.4+0/FastTransforms.v0.6.4.armv7l-linux-musleabihf.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "85fdb087da19a6a8563c5b5bfaaf100ba1664c14"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "85e355bd90958af1f8dab44299c83b5c4cc57772104f0dc841862d0f4245a8a0"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.4+0/FastTransforms.v0.6.4.i686-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "3e91f533c2cfd5939a34d5b17fd5770ef1866a2e"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "42c19728d72224c86c87a7a8021da930a6913f650d3a530b0d8766cf3de91078"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.4+0/FastTransforms.v0.6.4.i686-linux-musl.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "d0190d466ab32bd1c2a3dd9dcf88e88bdf2388b8"
os = "windows"

    [[FastTransforms.download]]
    sha256 = "76672efaef00b919e6efade1f53a7f865f0eaab4d9acc2b0dd9c62832b580a42"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.4+0/FastTransforms.v0.6.4.i686-w64-mingw32.tar.gz"
[[FastTransforms]]
arch = "powerpc64le"
git-tree-sha1 = "ad4c4d1a97ea38c70fec6fc8643c83b4b4eeb32e"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "3007c1e2c98afd2129ddc5b8e4987e2da60652ecf0dca18dea3cbce290edc655"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.4+0/FastTransforms.v0.6.4.powerpc64le-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "riscv64"
git-tree-sha1 = "17f7e352cc25751d059e4613a108400511f7845d"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "c9ff09ec645b72df65b9b897ca3ccab6e83a3257570b84199d7cbedfe32c9161"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.4+0/FastTransforms.v0.6.4.riscv64-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "d7f455db6ad63f16371657021e1e94154c41fb10"
os = "macos"

    [[FastTransforms.download]]
    sha256 = "29bb182cc827ef89452bdae2f706deb8767942d56d9d4030e3bcb1225528d3e8"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.4+0/FastTransforms.v0.6.4.x86_64-apple-darwin.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "bade22e9247324a8acc9e0c5c3cf9c16bcbe034c"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "d9dd4024c1d9f9abb3d497da2cb1fbf0a65a7f716602fb5b1da88c9e42831043"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.4+0/FastTransforms.v0.6.4.x86_64-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "c26322d21f7365de27d494fa8ca0c05d621cc594"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "d8fd4fb84a5800cbd2c3af8678c013a110bb20475005cbdef612a90f1ee9a474"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.4+0/FastTransforms.v0.6.4.x86_64-linux-musl.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "e54fb9f26e92ceaff8097515bda93a78daa1c783"
os = "freebsd"

    [[FastTransforms.download]]
    sha256 = "bd27a2603d10a35bce7cd9b1e27b846d08675239d553a141c8ee742594c6a540"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.4+0/FastTransforms.v0.6.4.x86_64-unknown-freebsd.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "a57e943df389e0e97d2efec029509850be047f0e"
os = "windows"

    [[FastTransforms.download]]
    sha256 = "e73f2dd2b247d6ea35adc8e9859406de706a9d7cdac8b4dd702a996674552026"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.4+0/FastTransforms.v0.6.4.x86_64-w64-mingw32.tar.gz"
