[[FastTransforms]]
arch = "aarch64"
git-tree-sha1 = "009343dc0c6ce86494e2ed3523f161605789a50b"
os = "macos"

    [[FastTransforms.download]]
    sha256 = "d9658065187469effe8c5475b8f02238de92853de61caf54823d95faabc958ce"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.4+1/FastTransforms.v0.5.4.aarch64-apple-darwin.tar.gz"
[[FastTransforms]]
arch = "aarch64"
git-tree-sha1 = "9bc7f48bd25e329ceee1dd5e591809147bbace65"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "7208a525986731605b4e25ae6ffb7c9a81618242da5582b5d720d335c97d10da"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.4+1/FastTransforms.v0.5.4.aarch64-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "aarch64"
git-tree-sha1 = "e05487319cba7c9af005e8fa6c001a16b5b02fcf"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "9f32f63f67cf61cd5efaf22070fdafc93a5b81f3f95135a74f53fbff8a45bff6"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.4+1/FastTransforms.v0.5.4.aarch64-linux-musl.tar.gz"
[[FastTransforms]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fb4719334e3cc75505d27b0640def334ee6529e1"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "3c06f099adf0c3bbe498d7c006a98ea4c8879d7518791281c204170fbdc9fd82"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.4+1/FastTransforms.v0.5.4.armv6l-linux-gnueabihf.tar.gz"
[[FastTransforms]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "28af86cc8f4b990a8f3481c521237542d528de06"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "488b927461ae88eca204e4dcb8e6dc57b7aa350f2920b9858a81982bb8505944"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.4+1/FastTransforms.v0.5.4.armv6l-linux-musleabihf.tar.gz"
[[FastTransforms]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "41fcc242188d115c2852273c63b84b4f0cb3eb8a"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "2b8102dfdc56f9b199029c96eee84fb25f340b069cd6af1d095006c0869421f0"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.4+1/FastTransforms.v0.5.4.armv7l-linux-gnueabihf.tar.gz"
[[FastTransforms]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "83aaa7de5ad34e54e75592ae1cd800d1ddbc483c"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "5b428698abfce9ef838ed31e5b1dd5a9fd2d630ab64585ff93ab56bc99797431"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.4+1/FastTransforms.v0.5.4.armv7l-linux-musleabihf.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "d7387037a6858b121023f76864af9161d51d9057"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "028e534a571dc50ee6f3ae0b2fbfa22129ddaf9634e0a1efb01cf32ed01e2c3f"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.4+1/FastTransforms.v0.5.4.i686-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "e85ed56022d4d5e943a574d7189408132a7eb145"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "83687db70d05b0ac7d3c4130132523bec8259ab7edc1f57d56828a3aedc50666"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.4+1/FastTransforms.v0.5.4.i686-linux-musl.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "ff98db968e539723795a3da553b83e526759368d"
os = "windows"

    [[FastTransforms.download]]
    sha256 = "4f36db1c4b1f63727afb93febd3b47dfbfccc8ddd4b4f79504c32ca3e7100f5d"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.4+1/FastTransforms.v0.5.4.i686-w64-mingw32.tar.gz"
[[FastTransforms]]
arch = "powerpc64le"
git-tree-sha1 = "3b338daae8f19f1c747379c42d195970b9c96528"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "98511dbdfcfd5a53d153fda09aee714f84119dd374a5485356aec239ca553977"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.4+1/FastTransforms.v0.5.4.powerpc64le-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "ed5b120422a59b9e9c9f97020291f17d7f8ae482"
os = "macos"

    [[FastTransforms.download]]
    sha256 = "08865f8ae1a48d6ec05a1915c86d6bb26be15b5c4513fee5528113996f5c5a1d"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.4+1/FastTransforms.v0.5.4.x86_64-apple-darwin.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "41d0fb7720cdc6ea4d98a8cf6efdd99dbecfbf5b"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "e9e683b4719a2f61bfd82053f10a2913b8209e9e0868652a375149d8121db4e7"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.4+1/FastTransforms.v0.5.4.x86_64-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "a189dd8a817f1c63f52bdc9d7b07331c684bfeaa"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "545f7467e1f447b3c7853e3eca8db7021201887a0ec1fd1faf70f5ae95fa1a6f"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.4+1/FastTransforms.v0.5.4.x86_64-linux-musl.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "19b30c63c89b6d7393886bb6a4f4c8ea6004f5e1"
os = "freebsd"

    [[FastTransforms.download]]
    sha256 = "dc5bae93dfde48c75e205ff045151887b13130cdb6b60a87c5026fefcc396f28"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.4+1/FastTransforms.v0.5.4.x86_64-unknown-freebsd.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "0fe6c79bce31da8e182b2ca109ae9f25b0a40738"
os = "windows"

    [[FastTransforms.download]]
    sha256 = "53769e804b97cf4d63184e1c20331a8f953fa91e331c67899cfa9f3e59ca7760"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.4+1/FastTransforms.v0.5.4.x86_64-w64-mingw32.tar.gz"
