[[FastTransforms]]
arch = "aarch64"
git-tree-sha1 = "1fa54f0f990773edcaa5a72b8e2e170fdb947330"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "c7251a1e337f887c7f01f141c651f58e9258ec583adf12304192987823dc4021"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.3+0/FastTransforms.v0.3.3.aarch64-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "aarch64"
git-tree-sha1 = "e080edb968962079a33a2e03fa10703be320a23f"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "73b6098db2d18469fe093c5c6a5854537abb24dbe985be74bf93e0f8640406d9"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.3+0/FastTransforms.v0.3.3.aarch64-linux-musl.tar.gz"
[[FastTransforms]]
arch = "armv7l"
git-tree-sha1 = "f8eb2f3aa430c1ea80c46779ba89580372f0f0db"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "f3de2f7f1734c301099ebd62b4bc38042d0f3aeb3bf900e50d8ae05dc74a6155"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.3+0/FastTransforms.v0.3.3.armv7l-linux-gnueabihf.tar.gz"
[[FastTransforms]]
arch = "armv7l"
git-tree-sha1 = "9f3210f78d002ed1b66208e0a176a872d6b66ff0"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "47d8c6a026ce1de038492bbbffa46287a586f9d393502b15b9818eae3c8d1126"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.3+0/FastTransforms.v0.3.3.armv7l-linux-musleabihf.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "d4ffed937a323914b8e15d8f6e9ea0d01ccfa23f"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "8d89bf6b2c5e8aa7ae57aad119ab125b124f299768bfcb57ed5cd5c729f8efe7"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.3+0/FastTransforms.v0.3.3.i686-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "8395705f075b1c991c989e5d7b4898b970b5ea7c"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "58d09060c3846af0d517e6a99fd2ba1ce355923a4b2e84e1c2a6502b37ce76c6"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.3+0/FastTransforms.v0.3.3.i686-linux-musl.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "98a6a903f95390cf18ef9ea14123afb9ebcb0ce1"
os = "windows"

    [[FastTransforms.download]]
    sha256 = "bb94b35663b16c976370a8357d3a19ea0106dc90c0736150b0cbc7add4516d18"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.3+0/FastTransforms.v0.3.3.i686-w64-mingw32.tar.gz"
[[FastTransforms]]
arch = "powerpc64le"
git-tree-sha1 = "8cbe7b92399a3191821f5412002055dbad64f767"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "8e06d3fd3e50e2a0135f224bcabe740db0a9f2580cfc42aa3edd12266c3dd1ae"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.3+0/FastTransforms.v0.3.3.powerpc64le-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "c19679d35053e579649787dca74ea2a2309c65bd"
os = "macos"

    [[FastTransforms.download]]
    sha256 = "cd6f18ce6becc5b047ce5b30a872f99119d014696646dbd43c895f757f9fe334"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.3+0/FastTransforms.v0.3.3.x86_64-apple-darwin14.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "9b0a08e35db7d9bebae2d3bc8333705d5be92f05"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "693b4e750408b715a1f321219dc6c961e608a3b6ae5c5b26eca42531c94f5686"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.3+0/FastTransforms.v0.3.3.x86_64-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "a91a0dba31b2d19338fb3c0401125d9d0e9a59c2"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "b712d041ad4944da49a54be9dc239fdf44b4fcb17eef791f419357073fabeeac"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.3+0/FastTransforms.v0.3.3.x86_64-linux-musl.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "f270b814262657f9adc7912452f95bd89138abf4"
os = "freebsd"

    [[FastTransforms.download]]
    sha256 = "b9abf9399256d77f7566e59a2df96ddcedc4eef64013e19559c57139d8002d66"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.3+0/FastTransforms.v0.3.3.x86_64-unknown-freebsd11.1.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "757b2ab7a1bb556f2bc65081729d2513524a2ff9"
os = "windows"

    [[FastTransforms.download]]
    sha256 = "0a88f96ca92957e96768ca792053caa2e24487b4fc592c25f75846d8a88b4117"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.3+0/FastTransforms.v0.3.3.x86_64-w64-mingw32.tar.gz"
