[[FastTransforms]]
arch = "aarch64"
git-tree-sha1 = "12239dc898733de38ce117ce40b8483652a9438b"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "66866c9d69ec369bb8024d651a40a7c3ce85dd3d74c7ef4915704231fbcd11be"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.4.1+0/FastTransforms.v0.4.1.aarch64-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "aarch64"
git-tree-sha1 = "d68082dcbc4caf2328ea8b3aa8d16988352fb782"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "03d774ea844bb7ef779efacdd7d6a5044a90e4d03b1e66d5f4e847ca0cc3f905"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.4.1+0/FastTransforms.v0.4.1.aarch64-linux-musl.tar.gz"
[[FastTransforms]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "46566cc1726c3671d4e85b40b52d56248ad2906b"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "eed7303ff592da96b87ec98f878eee4a2333a428b7bb36faecbb59df00588b07"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.4.1+0/FastTransforms.v0.4.1.armv7l-linux-gnueabihf.tar.gz"
[[FastTransforms]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d446ae2f93e902d787e4df82fc8d34c2b9779892"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "1cd4d05dd0d62584a53bcc81ff1a455a9370c4d962ed346423f1c86f08b933e6"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.4.1+0/FastTransforms.v0.4.1.armv7l-linux-musleabihf.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "85696342805de8b389066fff6b4c635c8d42cc90"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "e03e04c787807ea680b3f6e410af2e5a1cbf78e873727e92c8d6fe4770b1691e"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.4.1+0/FastTransforms.v0.4.1.i686-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "933817fdb178265440df4a3f0e9110c115ff4993"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "dc0a86a11d6e0c7ddf259b2daa74ed9cd7809cd6c26b240d6efa510f19caacb4"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.4.1+0/FastTransforms.v0.4.1.i686-linux-musl.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "3fb43dc427db6794fca191cf77202a9bdc4a1692"
os = "windows"

    [[FastTransforms.download]]
    sha256 = "945c8a9737452df31ff1e3d147ddf30083e0f24bd3888112d3a082fef1d4abac"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.4.1+0/FastTransforms.v0.4.1.i686-w64-mingw32.tar.gz"
[[FastTransforms]]
arch = "powerpc64le"
git-tree-sha1 = "57b5374f1f1d19cc8774ea9198c07bf601f36053"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "d603d207b3b1c87b3222fd544fa94c74d964ba359efef428de6f67526aec5cb9"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.4.1+0/FastTransforms.v0.4.1.powerpc64le-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "14ebf2079dd3734114ea87063e7c6ec13ad42063"
os = "macos"

    [[FastTransforms.download]]
    sha256 = "5a83f11b50b749273f8a5ed5a007df914bd579d19c1522f5cd5c3b512a5bca36"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.4.1+0/FastTransforms.v0.4.1.x86_64-apple-darwin.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "592f2f5621a6e7424076b5dc52f1b3733c6abd63"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "cae059f6b3e586a2a9806dccc079e9ce78a0a7402d84b1c4d3305eaee65987a4"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.4.1+0/FastTransforms.v0.4.1.x86_64-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "b9a6274b1115507fec127a58de08f743c7890a58"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "494a334d6f264dc15438abaec7519607791316c5195285e10629b48ce39baef0"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.4.1+0/FastTransforms.v0.4.1.x86_64-linux-musl.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "fd8b07f7724e968e831dcf463f2b8f3eb178e4fb"
os = "freebsd"

    [[FastTransforms.download]]
    sha256 = "0a41a6dd3362dc6753ea1a481091c24e9ec8e0aea70421e2c7262af7034a4472"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.4.1+0/FastTransforms.v0.4.1.x86_64-unknown-freebsd.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "256574a2ab32e0bcc338cf60228802c6e1059857"
os = "windows"

    [[FastTransforms.download]]
    sha256 = "e7574d4412d8a505c5b36489f1969c74a96c0d2bea3fed570953b21212eba48e"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.4.1+0/FastTransforms.v0.4.1.x86_64-w64-mingw32.tar.gz"
