[[FastTransforms]]
arch = "aarch64"
git-tree-sha1 = "894464ccbac6fa2f1c797cbe92ec810833229813"
os = "macos"

    [[FastTransforms.download]]
    sha256 = "3aaa1740703ec69e0ed58f31654aaacb5b92502c7667877515803c995f3a595f"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.0+0/FastTransforms.v0.6.0.aarch64-apple-darwin.tar.gz"
[[FastTransforms]]
arch = "aarch64"
git-tree-sha1 = "368506fa5cbed14c5c7350818fea3d2d2d66a165"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "470ee107e0d7b124994df19bd67364619d1a42d89035da5e58794b6333624b39"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.0+0/FastTransforms.v0.6.0.aarch64-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "aarch64"
git-tree-sha1 = "225e42c1a269182352bd712bd3a24884b47c4e26"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "2fc6375b6a606a2bc6909bb4e852076ddd28bf4c89a259ef6a0a85c346a4dc36"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.0+0/FastTransforms.v0.6.0.aarch64-linux-musl.tar.gz"
[[FastTransforms]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a033569f82128e8574f356d3c1eb6a4f57ac12b7"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "3d7018123103e6e76ce020fd1df85b50866042bda9a4e27de4273e072726ac26"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.0+0/FastTransforms.v0.6.0.armv6l-linux-gnueabihf.tar.gz"
[[FastTransforms]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d6c8fb7f9d2bb97be9bdebd750de6bbe87301b36"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "047aa3479636088ed4026e2140011ce78066f26760210c979e7d767589873f76"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.0+0/FastTransforms.v0.6.0.armv6l-linux-musleabihf.tar.gz"
[[FastTransforms]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "82b26e3f0544bbaf20c8c3d43b3b26a1f4830f29"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "047ea9ebdf14e72086bb5b1b689879a4fcc413f348febf2d9cbfb43ea5f461e7"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.0+0/FastTransforms.v0.6.0.armv7l-linux-gnueabihf.tar.gz"
[[FastTransforms]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "20c5f4f5485ff7616c3ff059623abe40d8a76b9e"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "7013eb5699a85b88c2a2fb9cd3cc7187719525a57a42513f5668ae1b5133a2a4"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.0+0/FastTransforms.v0.6.0.armv7l-linux-musleabihf.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "a313c91b7dfac6558cacab95c6d6087836076b15"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "7114b2027e85010706bec5c2e527457b0efb1dd20becda948c8d803648bccba1"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.0+0/FastTransforms.v0.6.0.i686-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "694f4aa9b100402da04f8740424fc2f9d0cda0dc"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "36e44314b4454f5522038a4ab5af3fb9e8214c682527b602aad27c83114b125f"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.0+0/FastTransforms.v0.6.0.i686-linux-musl.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "b5a29b39f61e999c36e998a9e050489079999bff"
os = "windows"

    [[FastTransforms.download]]
    sha256 = "adebc7e1443fd0306f723f52686220eb116b3ffa549ab6e124e93941537e0a35"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.0+0/FastTransforms.v0.6.0.i686-w64-mingw32.tar.gz"
[[FastTransforms]]
arch = "powerpc64le"
git-tree-sha1 = "6edd8d4ffdeb65d33eba87f266a81f3ad7ab8c6a"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "13540f3b82d53ecc963b1674b174e743f7e80e992dbd6a330f552582169de098"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.0+0/FastTransforms.v0.6.0.powerpc64le-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "f0f10168612c9af7147248b10227d216ba47afd4"
os = "macos"

    [[FastTransforms.download]]
    sha256 = "8a0a9d56d46c663350e7c826fc2f35dc0a7f76b483af77382fa8911215fd4e98"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.0+0/FastTransforms.v0.6.0.x86_64-apple-darwin.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "05e3db9ad2b757da4641a193775c61e401405713"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "4a449e301afa9b12d135c1dcd1b03f8b7a11593c210183c129a7db0f3115b8a2"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.0+0/FastTransforms.v0.6.0.x86_64-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "0f174f10f7718d1b74ccccad2dc5886721f67a3e"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "746ae6aa648cfdc02bca501c8bab1e5dadc3bf472304822ceec7dc6c68e2d330"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.0+0/FastTransforms.v0.6.0.x86_64-linux-musl.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "66c45f0cc70349f0de3d9b88fbd6c4bc8b6d7e7d"
os = "freebsd"

    [[FastTransforms.download]]
    sha256 = "1de122bd35d0d2155526b5a30955cdce46208a1b83cd413c018734d6225002ab"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.0+0/FastTransforms.v0.6.0.x86_64-unknown-freebsd.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "d226cd8ab9b2980c5c6aa431a5faa18b2571fa10"
os = "windows"

    [[FastTransforms.download]]
    sha256 = "16b4f566d8514e59939988fcaf3276c8199db0b5635187b1bd7a3739f0dafcbf"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.0+0/FastTransforms.v0.6.0.x86_64-w64-mingw32.tar.gz"
