[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "8a22ad959c19200a68fa7fd84b5983f64ca0726e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "e8f2c6e25dbdc6a7a95211aa513e1ce765282c7534a2e9aa333ef17769b439bb"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.1+0/FastTransforms.v0.3.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "28b43d4b20809f3c2d672b022dab8c6c3d05c063"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "4074954a66b4eeb44b961b68ec0fa0e5e241e6059f90d529e6eb6882db4af45d"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.1+0/FastTransforms.v0.3.1.x86_64-linux-gnu-libgfortran3.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "0c78b07390d29b4b4e5bc8fb4935138bdc2f0abe"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "cc18b999eb99f98e6dfa1a0ff993dabaa8538bed3ffeb4ecb49127e16333dbe6"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.1+0/FastTransforms.v0.3.1.i686-linux-musl-libgfortran5.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "e3b14de4ce28c9ae556ed8eaaee6c93396b14c23"
libgfortran_version = "4.0.0"
os = "windows"

    [[FastTransforms.download]]
    sha256 = "c04b68d712d8775f9c280494c52f0bc8b3b73ce3943ba35e02ca3b0f408cd373"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.1+0/FastTransforms.v0.3.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "3c040414783fbdad82f95361e9fba8ca28d416e4"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "4922b0a37e875014849747cd89b598e82277188f0bf1fef804a5f9851995e91a"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.1+0/FastTransforms.v0.3.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "a6628e92ffd63e3d74ae601d5c2611414c4beb75"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "bae62898884d79b99382f8cb7e99930db58a6e254004d611c835e6f29547bd4b"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.1+0/FastTransforms.v0.3.1.i686-linux-musl-libgfortran4.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "fed9ff87c791de0f83324929ffab747eabb66a63"
libgfortran_version = "5.0.0"
os = "windows"

    [[FastTransforms.download]]
    sha256 = "3ec4a83278b7c8f0cf2f243fb280bce4db411657e33ea0d71d1474ed9014125f"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.1+0/FastTransforms.v0.3.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "3408bb629360c6c2d11e17d7ef97c3d40e40badf"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "38c6c1779efd6985a98c37df1cf9a6603e54d26334b3a4b7a7313f99176d2ca3"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.1+0/FastTransforms.v0.3.1.i686-linux-gnu-libgfortran3.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "967fe945109e966ad06ba170f5c0f6e7dfc63ccb"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[FastTransforms.download]]
    sha256 = "ba838aa92337d0358ada784169d506b46edbb521b88bd731808e9b20329d6aa6"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.1+0/FastTransforms.v0.3.1.x86_64-unknown-freebsd11.1-libgfortran5.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "913689cde1c5cc3fc2b75bff0cb358d0f677d5e3"
libgfortran_version = "4.0.0"
os = "windows"

    [[FastTransforms.download]]
    sha256 = "9b7cfa1abf064bb6ff131aae7ff33c568ca73e0ff4d1dcc3082ba96ec75a0c24"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.1+0/FastTransforms.v0.3.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "79074081220b79c1b99352e6fa672345639b9299"
libgfortran_version = "4.0.0"
os = "macos"

    [[FastTransforms.download]]
    sha256 = "1e6d14d1d4b198b45504e1162b3c2e77d1a2b7c9718f5ae0852a1091dcbb01c9"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.1+0/FastTransforms.v0.3.1.x86_64-apple-darwin14-libgfortran4.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "97a43c97ea6894c7c6a98d34ae007890dfb5cce4"
libgfortran_version = "3.0.0"
os = "windows"

    [[FastTransforms.download]]
    sha256 = "cf54cf4810d2accbe052d55e3e17bd9c140bb5c62c54463c10b801fec3d9de36"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.1+0/FastTransforms.v0.3.1.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "ee84ebba6e78d90d5783b21d7f01c9d12a8f2a8b"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "7e581ea98e159b65417a29bfe02614f41b2fc6a5d76ac0d529c83203af58d890"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.1+0/FastTransforms.v0.3.1.x86_64-linux-musl-libgfortran3.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "cbf42b64d34334d6e0bec9106d2af4f556c5afe6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "b411f74ac35b5555cc5843117c5bfca84bba11983c0ee0b81167b2a8dc7cd07b"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.1+0/FastTransforms.v0.3.1.i686-linux-gnu-libgfortran5.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "1ae18865b702938929d1935513ebeb5e0010cc16"
libgfortran_version = "5.0.0"
os = "macos"

    [[FastTransforms.download]]
    sha256 = "80fe30aeea70ee72c45047205ef83031cb981865bb2cdeb2bc87d7f347116501"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.1+0/FastTransforms.v0.3.1.x86_64-apple-darwin14-libgfortran5.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "69afb1044b8efe06d8da46649e0de11b89cbb35f"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[FastTransforms.download]]
    sha256 = "2acbd30ff398d275ab2f074e21f4efd25ebedb1857a158000f5f7154e6f4122d"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.1+0/FastTransforms.v0.3.1.x86_64-unknown-freebsd11.1-libgfortran3.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "bfc46b93ff707a397951e1bc3befc4dbabb87651"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "6e6b03b0cb1ad858ff58df3ba7c538bbda4cf6a508baf7b1a0e6b87e6f4bb50a"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.1+0/FastTransforms.v0.3.1.i686-linux-gnu-libgfortran4.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "3bb95b86a39de6b9efff24e85d92d86139c84239"
libgfortran_version = "5.0.0"
os = "windows"

    [[FastTransforms.download]]
    sha256 = "55b827aa3735666a463c64b859c1fbc9538a349b0fcdede40c43effa80fe99e3"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.1+0/FastTransforms.v0.3.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "451312c0e7d0ed28139a067eb1d4805f5d8e99d6"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "c19352d7e00b677321455c1f3373d85573c4084514a563d3655cd39bba3cdf62"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.1+0/FastTransforms.v0.3.1.i686-linux-musl-libgfortran3.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "35ed5e4a1afe3704eb4616870ff54472f37c2d3e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "99f96b71e7ec486a54444984d17cbadccd424aee559218919712b3d3f98c9469"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.1+0/FastTransforms.v0.3.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "332b63352a2a3647ca93dc12c32f306b19014a6b"
libgfortran_version = "3.0.0"
os = "windows"

    [[FastTransforms.download]]
    sha256 = "8885fa9d782b11754d558abf46341aef07a79d55766d944f9382bcde713f0962"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.1+0/FastTransforms.v0.3.1.i686-w64-mingw32-libgfortran3.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "50dbb99305fb49d32c79d8ee9d2045f0c6fbbcc8"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "c398a6975aa973748c8aa1d4c84fa001689acef032303ef4a8b466d61ddfa9c4"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.1+0/FastTransforms.v0.3.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "8e327ee67b3a275a3a7d519638c8fb77f045ec7e"
libgfortran_version = "3.0.0"
os = "macos"

    [[FastTransforms.download]]
    sha256 = "b43e37d45d0d573b602c378a4d4044c8526b4e6cd711d701c0e38481dde12dcb"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.1+0/FastTransforms.v0.3.1.x86_64-apple-darwin14-libgfortran3.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "e83b4fd4cb5c6c087dd3d132be7077d801f35620"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[FastTransforms.download]]
    sha256 = "0c07aa2430aaae0f84ec4b8832a32309445974b9b3fbec56914c67f41dda9ae9"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.1+0/FastTransforms.v0.3.1.x86_64-unknown-freebsd11.1-libgfortran4.tar.gz"
