[[FastTransforms]]
arch = "aarch64"
git-tree-sha1 = "edf00c51aa8d4a5b36902ad220fbdc05c74cfd49"
os = "macos"

    [[FastTransforms.download]]
    sha256 = "9dc2b7711d21eea6ffb93702ef34aaea2b0f87e7bac2ca6a3102f3ed2d80b482"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.1+0/FastTransforms.v0.6.1.aarch64-apple-darwin.tar.gz"
[[FastTransforms]]
arch = "aarch64"
git-tree-sha1 = "a3eb4d0548bb3b32bbcd42fc00f43fa30dadd790"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "e03fe5959ea2ecc951a29c586f510f2485fd659f6b90fdf0d1e61f43368a1c9d"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.1+0/FastTransforms.v0.6.1.aarch64-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "aarch64"
git-tree-sha1 = "0e34b066ed771738550e65e434eb0b81702659f9"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "ac993b3a46da0020cbb4a9d11edce754e825c8fa441399bf0b3bf399573dd481"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.1+0/FastTransforms.v0.6.1.aarch64-linux-musl.tar.gz"
[[FastTransforms]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6d3f3d8a4c896584e03508775ca100c3510efd49"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "4fffb7501827de0860744a3e7c1ace43c6cb921f4db7ddce4f6f4d85e446df3f"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.1+0/FastTransforms.v0.6.1.armv6l-linux-gnueabihf.tar.gz"
[[FastTransforms]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a2cbad11184a2933e24787a182a377aa203793be"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "863c171b6ff8cdec01fb7c2dce9a120ab10c5202b60308839d9e99b11305a598"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.1+0/FastTransforms.v0.6.1.armv6l-linux-musleabihf.tar.gz"
[[FastTransforms]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a16e2c0ea835561f6f16a91e85593d9c160bf48f"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "e02bcbe5caad933f31ed50204c9abc514f470122f08a93a1842491d930b5a1a5"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.1+0/FastTransforms.v0.6.1.armv7l-linux-gnueabihf.tar.gz"
[[FastTransforms]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "07023add20222b61664c99d6fcd0c38943a5b138"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "cfcf5950812218a94ed99e9ad07ee4422f375d25bf28426c37979ab7df82ffcb"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.1+0/FastTransforms.v0.6.1.armv7l-linux-musleabihf.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "e434d398c744574b5175b53e81717cc91ef51e47"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "9cf6a664babb94e1363a708fcbf2965551a1ec842bcccba347cd46db047cf12b"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.1+0/FastTransforms.v0.6.1.i686-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "bdaad5f20d6b63fc510211d70ead2f7c74fc4674"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "7848ca683fde6dba72d905b30fdb00f122a1554959f65a3063e750276dafcb24"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.1+0/FastTransforms.v0.6.1.i686-linux-musl.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "8716d2f394f7f37c88ab5d2ef19325123338596a"
os = "windows"

    [[FastTransforms.download]]
    sha256 = "c904343aca88f4b8019d2264f1f515635e81412e12cd96b826daf3b9872055d6"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.1+0/FastTransforms.v0.6.1.i686-w64-mingw32.tar.gz"
[[FastTransforms]]
arch = "powerpc64le"
git-tree-sha1 = "311bf1777785a0d72db04631087784567e2384f8"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "cbdc13c9f473ec0eb18d6bc4564540113e5d60248fd8fec349b5d2cd659d2229"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.1+0/FastTransforms.v0.6.1.powerpc64le-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "3d5a5b8a53ba5a1189e51db1b2ad7e725d76f19c"
os = "macos"

    [[FastTransforms.download]]
    sha256 = "37090939cf72e62dfd267d30eb9c0296e72e0036cad9a34dd6cadfd682157a96"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.1+0/FastTransforms.v0.6.1.x86_64-apple-darwin.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "2c3f222f4d511a5abd03919d5f3cc5fecaf14cde"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "8e6ac69c90c26f212771f02bec4dda3e420fe373739af1e658823677296057e2"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.1+0/FastTransforms.v0.6.1.x86_64-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "932e9ecd22aab16f54b71a5fa5b5c56f92e05ee6"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "0131102d6ed64560095e955dc63e6fb59c4af3ef34bc5ff2e53fb7ef65b461e2"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.1+0/FastTransforms.v0.6.1.x86_64-linux-musl.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "63b075c8608d470f10c24c191d18a4aa45b7aa69"
os = "freebsd"

    [[FastTransforms.download]]
    sha256 = "93dbe864c819c9b90f2cbbf874cf59259f2069955bf630c85fba890588b4cea9"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.1+0/FastTransforms.v0.6.1.x86_64-unknown-freebsd.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "bd71a67bd5deb939d4de4b1199f6b567622ebc62"
os = "windows"

    [[FastTransforms.download]]
    sha256 = "76d3322ff3c01bdc6e496285f9f0c72291f095b4cf5facaa3399f5c003929a66"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.6.1+0/FastTransforms.v0.6.1.x86_64-w64-mingw32.tar.gz"
