[[FastTransforms]]
arch = "aarch64"
git-tree-sha1 = "6a434cd0af47e56858cc1d73c596c56de8fabe86"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "625424ed21fe03eccb5a5ea2fc04dad542180fe083db81c2eaec5754c56ccf8a"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.1+0/FastTransforms.v0.5.1.aarch64-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "aarch64"
git-tree-sha1 = "aed5558736a5c46f355700bd4d667a681f467fa4"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "85f09b2e0da46eb7dc7d7b1337b8b2297977d6fc15e91578a84014bcbd30cfd4"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.1+0/FastTransforms.v0.5.1.aarch64-linux-musl.tar.gz"
[[FastTransforms]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1459056d5bcb301e17272daaa070299f0b833dfa"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "0261f8495401dc26512e31ced5b7eadf9d24795d26fbebb1a6c0e69c3095d45a"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.1+0/FastTransforms.v0.5.1.armv7l-linux-gnueabihf.tar.gz"
[[FastTransforms]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a38b8b66213b4cbcdf94f70fc710c93b2770ebc3"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "c5d53d2a479ed0a0b39605b831ed7abe17deb3df9becd1f56061a71a3e2085ab"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.1+0/FastTransforms.v0.5.1.armv7l-linux-musleabihf.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "58fcd7f307918ad234f7e72894bed352e5272595"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "6149771cd26ed82d57d35bc588eac9feeb26c088ef84aa0f74e08716b12c7f9e"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.1+0/FastTransforms.v0.5.1.i686-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "aaa569bb51357b5eb126fc546f20602e7b798630"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "84d753d66017323caa93cbd9b0f57d49673c174bd3c45a6d042ea22976b1b27e"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.1+0/FastTransforms.v0.5.1.i686-linux-musl.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "42ba55a514f374aee88ffa6183988fdd2c2d7fd9"
os = "windows"

    [[FastTransforms.download]]
    sha256 = "e6f09ed4ad5a37600bb1379363e73f6365896dd49f3de61fb916e0a0863d47d8"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.1+0/FastTransforms.v0.5.1.i686-w64-mingw32.tar.gz"
[[FastTransforms]]
arch = "powerpc64le"
git-tree-sha1 = "d5ef110949521ac9328826e991e1c45db33fd577"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "ce4a06bbf59a23bbdd973e2cd6c60f9de49980355ae3450d55a94e4631ee6330"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.1+0/FastTransforms.v0.5.1.powerpc64le-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "8047bf4705a460e8fd2bcc0959fb3514e7ee5388"
os = "macos"

    [[FastTransforms.download]]
    sha256 = "2446cb06d92a047a6a56bc1af82d2c970d6952ee752573e281933f05175768c4"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.1+0/FastTransforms.v0.5.1.x86_64-apple-darwin.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "603bf763f4eb68f8445d34a461cea3c8156cae18"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "6f0f44f5a46d6ec96600f42a0cc68383f0f223ce6b20cd1cf5df9fe82a8a78ba"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.1+0/FastTransforms.v0.5.1.x86_64-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "cb2cfe15ce164f1624794f61d4b14790f0c4b9a1"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "1895c0cb6b2d6f12522ac6211a64dd4122f4860a3e075d10bed54a97e7c3b994"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.1+0/FastTransforms.v0.5.1.x86_64-linux-musl.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "7acbe70dfe9e0f4e970def9b7ce397d403c7b5ba"
os = "freebsd"

    [[FastTransforms.download]]
    sha256 = "6d791db24144c6a2a3fbd4935179ae7b4af7d8d9c308569e1c8c13a72f314783"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.1+0/FastTransforms.v0.5.1.x86_64-unknown-freebsd.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "ac5ef189d38bf14ecfd115e9e4e9a52bd486a54d"
os = "windows"

    [[FastTransforms.download]]
    sha256 = "49ed52a979f33dbb3e7a93141dcddb4afbea8a3ecebc9000726d5ac53a7582d8"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.5.1+0/FastTransforms.v0.5.1.x86_64-w64-mingw32.tar.gz"
