[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "8a4b7722ff3f5ce51788a79e1031d3a5e9b1ed2b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "4c220e90448513acac6c73c5543ec23758d303c006dd665916e583caaf2a64a0"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.0+0/FastTransforms.v0.3.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "588c8ad3fd61cb06aef817a942592a5097ce7702"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "ac3276701b6001d2ae7adfc5c8e20dba55c4594c08ec2067feb58f959aa00470"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.0+0/FastTransforms.v0.3.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "b613f9e3ae8593f3b65a3a282daf433a138ef768"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "b14592ddbc32a6c7365a6d73b040aeaacfcc4e7816bdf470f19b51014b45bf4a"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.0+0/FastTransforms.v0.3.0.i686-linux-musl-libgfortran5.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "e63e51c1298b88d1558e9bcf5f79c2890df94e82"
libgfortran_version = "4.0.0"
os = "windows"

    [[FastTransforms.download]]
    sha256 = "4ddad93ae282fb31364eb71dca34bed52e78437b671b49bd0c2331931a62af33"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.0+0/FastTransforms.v0.3.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "76503d774735d18ddac625e1aaa6ff29bddf87d3"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "9edb39c80d93d84d387e9f50bd10d265c6529c0be6da8a05e2285a002d203dd2"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.0+0/FastTransforms.v0.3.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "9fcf57ce2cfc095acf755d0999a260aeeb5a6788"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "5f36ccf3cb2b67e35c0c0cb401504776a8749f2359c308b31ef139c07e28cd9e"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.0+0/FastTransforms.v0.3.0.i686-linux-musl-libgfortran4.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "1ade37988964aa7f66921a5f79910eb9bc5b064c"
libgfortran_version = "5.0.0"
os = "windows"

    [[FastTransforms.download]]
    sha256 = "831c9be646bf23359201072cb113cc97edd52a0688e937edd6edaf4b44b85367"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.0+0/FastTransforms.v0.3.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "3688f039b8f6225114fdf86c4f0379f64147e943"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "2d82de1f37a572b26ec016043fe8399010a67715808eb0604f5a5932e7fb5f90"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.0+0/FastTransforms.v0.3.0.i686-linux-gnu-libgfortran3.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "ce15f62106f5cedf49d4b99bdbb7cc3ee3af6107"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[FastTransforms.download]]
    sha256 = "3dc979525e9fb49fcab0af78c62cdbcc991ca2b3be9d3d3625a967aecb04bc23"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.0+0/FastTransforms.v0.3.0.x86_64-unknown-freebsd11.1-libgfortran5.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "ae814db22b47da6db05ec3dbd097d91db026b91a"
libgfortran_version = "4.0.0"
os = "windows"

    [[FastTransforms.download]]
    sha256 = "d41f6dfb9da06c5aa9e615376bbdd90d132731b7d06fe8e087918d7b81772136"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.0+0/FastTransforms.v0.3.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "80912d7aad25e022462e6184ad2cd4b2ba92218c"
libgfortran_version = "4.0.0"
os = "macos"

    [[FastTransforms.download]]
    sha256 = "cfc0aeb2a23d52a5c70c1157ac028be0825c4d5fda347efa1668f32a81ecf4f9"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.0+0/FastTransforms.v0.3.0.x86_64-apple-darwin14-libgfortran4.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "6edfb25c8a8406b5a07a7fcc51e3222ead0295ad"
libgfortran_version = "3.0.0"
os = "windows"

    [[FastTransforms.download]]
    sha256 = "02ec927b91c380c04ddef12aca0e13eba224ba79743e23f13cc6df4755054a0f"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.0+0/FastTransforms.v0.3.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "4e9c58fa2e851b654368277377e159efdb3c198a"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "248123f7804f2ddd3a10672e00ee26b06c769823b5acea603866348f15804db9"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.0+0/FastTransforms.v0.3.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "6e3a6ac00707b5505a3cf93138d3d04382da763d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "d7d75609fd174ad062476e1114e702446b7b01b9cfd9b39dc4df9dfdb9d14490"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.0+0/FastTransforms.v0.3.0.i686-linux-gnu-libgfortran5.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "815950f10268afc348f51d4f0f061fe9e770de94"
libgfortran_version = "5.0.0"
os = "macos"

    [[FastTransforms.download]]
    sha256 = "0f2ccc3d7e7835375036776048a569840af618a1fe3815282b031b95a874dc14"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.0+0/FastTransforms.v0.3.0.x86_64-apple-darwin14-libgfortran5.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "2a8d6bc5a36587e654aa9999565df44fa744d9a0"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[FastTransforms.download]]
    sha256 = "ac9cf4b11803d051812279851bd4dc81bdfa2a1c9c0010b832e1c527a57d2896"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.0+0/FastTransforms.v0.3.0.x86_64-unknown-freebsd11.1-libgfortran3.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "0388c2b7971dbcfc8c8aad9e5bf5fd382c336c01"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "0d55028e2da1926ecd1f8ff3f1e993118bb8832bf32942b43915f851aa427e6b"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.0+0/FastTransforms.v0.3.0.i686-linux-gnu-libgfortran4.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "27063c1914ff2bf463bdee456f0fa76b02704df7"
libgfortran_version = "5.0.0"
os = "windows"

    [[FastTransforms.download]]
    sha256 = "6ae9a3688c885726ec81c8d19086bc0b0bcfac58511fb55fa6c3f3f3974d8ab3"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.0+0/FastTransforms.v0.3.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "cdacf44d1b371766ad14ad9fa433eabdadf674f4"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "a06efae6a47a302713f365b5a93a7071c57a7882d25f7b8c1a79610cf5c843f3"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.0+0/FastTransforms.v0.3.0.i686-linux-musl-libgfortran3.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "9db12b006b9f46b3df909ad32cc26e54d301cf13"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "10bd5b6802fa056b978871a1788b705b12de103a45e2aab1a91ec36650280b37"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.0+0/FastTransforms.v0.3.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "a577ac2a0246ae517b0f381ef02de3f10bb4b084"
libgfortran_version = "3.0.0"
os = "windows"

    [[FastTransforms.download]]
    sha256 = "e6540d44eeaa90ab058b3d6a3d186a58cb4c47106363c5f489e689ba1c33415e"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.0+0/FastTransforms.v0.3.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "36e39a8d3b3046f7e2fedcd9228615dda1cd55b0"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "d4db46131a3795b636cb704c745dd13db02ed4188c2dd6d109f67e550deca7ba"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.0+0/FastTransforms.v0.3.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "fadc25b7022e2b1a5ca0e1eb628063e8eb94c3e3"
libgfortran_version = "3.0.0"
os = "macos"

    [[FastTransforms.download]]
    sha256 = "2ea924fec274ed5c11ec6bc89cf32722910341704171787fa52e0518a0b0eba5"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.0+0/FastTransforms.v0.3.0.x86_64-apple-darwin14-libgfortran3.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "2f3ed4728d07598d78ee350393592d087a13bcdd"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[FastTransforms.download]]
    sha256 = "556236a35ce9d98c49c336fa42696fc5b94a892ce2a8f2e4f0c50353f2c737fc"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.3.0+0/FastTransforms.v0.3.0.x86_64-unknown-freebsd11.1-libgfortran4.tar.gz"
