[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "0998437e19f28d05ce3b3aa06ea22e3b21c4808e"
libgfortran_version = "5.0.0"
os = "windows"

    [[FastTransforms.download]]
    sha256 = "8c12e573865329a3effd34a1b76f7cef9e50440abba06122bb1511afccf83330"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.2.13+1/FastTransforms.v0.2.13.x86_64-w64-mingw32-libgfortran5.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "574cbacff3f46af036690bf569ce57672c5d8354"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[FastTransforms.download]]
    sha256 = "21e55910f0846000e0485eaa45f0c349a238f8ec38bef746f16320e6bfbc1d54"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.2.13+1/FastTransforms.v0.2.13.x86_64-unknown-freebsd11.1-libgfortran4.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "bce480c0d61784f87584b5e7468960174a32e87a"
libgfortran_version = "3.0.0"
os = "macos"

    [[FastTransforms.download]]
    sha256 = "45db665ab58d3f9d674b920d098ca979c1d95b68c3a726bfdfab23bbe3ab3f0b"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.2.13+1/FastTransforms.v0.2.13.x86_64-apple-darwin14-libgfortran3.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "ae574c9683e5c844494adb70ea18ffc81a8a50f4"
libgfortran_version = "5.0.0"
os = "macos"

    [[FastTransforms.download]]
    sha256 = "b1dbe1112dcf18c3746082015154cc58428616957fc16829e4a86deda84ece40"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.2.13+1/FastTransforms.v0.2.13.x86_64-apple-darwin14-libgfortran5.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "e1a6a31aef9bba0aff699f2a1cae9079eb10bed6"
libgfortran_version = "4.0.0"
os = "macos"

    [[FastTransforms.download]]
    sha256 = "e82aa5df66b5c533e512d2cadf1d1b9d0e60709f2df30018f4747f01f6f2a8c1"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.2.13+1/FastTransforms.v0.2.13.x86_64-apple-darwin14-libgfortran4.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "5d86f3e0ca584fe07713f58387de888c5a1254d0"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "daa362824b952c881f2429ad8370c6101331bf8603b9acad771d61a87d31d622"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.2.13+1/FastTransforms.v0.2.13.x86_64-linux-gnu-libgfortran3.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "0427453fcfbb726bdeb9c3fd9b4e3fcd87c60a12"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "cd2d297860b0378473be3d1cb11e958c8416d4e7a918774cdbde0660f602570c"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.2.13+1/FastTransforms.v0.2.13.i686-linux-musl-libgfortran5.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "32c286c1d9a333f56d04c7003f7a675a41255bee"
libgfortran_version = "4.0.0"
os = "windows"

    [[FastTransforms.download]]
    sha256 = "45e1e6ac8fcf3003c4aedd55e2725217f4159a51a0eb03dea71a72d8e51b210b"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.2.13+1/FastTransforms.v0.2.13.i686-w64-mingw32-libgfortran4.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "d90284b3a95054c3e3b7931c8a55165eb4fe3ac4"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "bb98f1f650f8f0a9fbec4d8926e74879a4ab8275c9b252e3ed64d7d140e31178"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.2.13+1/FastTransforms.v0.2.13.x86_64-linux-gnu-libgfortran5.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "d9740af8b5cfb3bddd33d9ec6a5f5c71a9869d4e"
libgfortran_version = "5.0.0"
os = "windows"

    [[FastTransforms.download]]
    sha256 = "08cc860b2756df4eb90de822578e44b0d18835b434dd281416a87c53cf667930"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.2.13+1/FastTransforms.v0.2.13.i686-w64-mingw32-libgfortran5.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "14f5cbfd2d715e091b4a84cb648ddb35afcbf3ae"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "5791aa3cd5a23cd11c0b52521175613836af29981ea46d994c8772363a7da789"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.2.13+1/FastTransforms.v0.2.13.i686-linux-gnu-libgfortran4.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "57afb7eebded75ab8268f170d5369a28abd9b798"
libgfortran_version = "3.0.0"
os = "windows"

    [[FastTransforms.download]]
    sha256 = "d6253b04cce81a29db5f7eb6220819504d8cbc283d9ecbc071810886d8046b80"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.2.13+1/FastTransforms.v0.2.13.i686-w64-mingw32-libgfortran3.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "7d658c8ed846b61b2c194c5a2e25e486dd0faa77"
libgfortran_version = "4.0.0"
os = "windows"

    [[FastTransforms.download]]
    sha256 = "ec2009af42bfbad4fa753061ca088eb3afc21582e879688cac065174485c876b"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.2.13+1/FastTransforms.v0.2.13.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "acd00facddbfd92a13dec980fcb894fa6322a882"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[FastTransforms.download]]
    sha256 = "0cf249ea6fee9752250888b745b6a0404dfc27925161d4b74c023c0bee9483bd"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.2.13+1/FastTransforms.v0.2.13.x86_64-unknown-freebsd11.1-libgfortran5.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "2412024ff6786ece8c2252a25d1c1af80eb64d5e"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "d670b91d42d7325c1d202b2b70402db9c802e8e092a64fb04a0e26e54fcff461"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.2.13+1/FastTransforms.v0.2.13.x86_64-linux-musl-libgfortran5.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "afc3fd9584be02b823718f877a9349c1b3f6cca8"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "ecaffe58e5aefc1b43a2da0e2b044bf34f7ed035df1e815021f7b1b7c49d4b94"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.2.13+1/FastTransforms.v0.2.13.x86_64-linux-musl-libgfortran4.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "c335ba26e56c7fd5389afbff0fe0721867eb5f2f"
libgfortran_version = "3.0.0"
os = "windows"

    [[FastTransforms.download]]
    sha256 = "01f51f244be0f40fc58aa77639f594a95b9de3c7dfc44b51d666977edf5a69b2"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.2.13+1/FastTransforms.v0.2.13.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "570ae154cc1f532db019a33aa365d5445fc63f07"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "3fe1e2397205e96f27900ceef4bce4ed88c980816b84dcd31cf3199337805506"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.2.13+1/FastTransforms.v0.2.13.x86_64-linux-gnu-libgfortran4.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "8e342f51d10a45d2b17c160dbafdde445d8c6250"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "fb3a7b253aee0957eb5b2a6fc39c6c60589215a7d4abf7450d0529f193090dca"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.2.13+1/FastTransforms.v0.2.13.x86_64-linux-musl-libgfortran3.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "7fa03af90e811ff85c4a63ac3488067b9b082b42"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[FastTransforms.download]]
    sha256 = "a271bfedffcd1541f4448c690e402cfd4b9ff34fa8d132e4c98631070cfa073c"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.2.13+1/FastTransforms.v0.2.13.x86_64-unknown-freebsd11.1-libgfortran3.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "166a6563fa1391a603411b78e9d5947a33770047"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "7f5b7ca55c854827e43a30b4713c1aa25797e7daeb9e8f0d64a761c40e7f7308"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.2.13+1/FastTransforms.v0.2.13.i686-linux-gnu-libgfortran5.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "21e04caccc5ce84a6a0bb9813fc9593df270040a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "540f14cb5e6610ba13668025296448446ca564b35221e99098259372aa0c1de9"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.2.13+1/FastTransforms.v0.2.13.i686-linux-gnu-libgfortran3.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "13e89ec98327f00499838dcb999552db93fbc3b0"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "41f80a1036fa151aecf5f6fb496d55834e0ee4bda6a572ac146e6e36da5e4e59"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.2.13+1/FastTransforms.v0.2.13.i686-linux-musl-libgfortran3.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "94824be6227e26f7aecf4819d32620ba5397d20f"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "6dcb5db65ed48ff8a45d01e8eff7594b1882ac792a46f9d61600217626c68dcb"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.2.13+1/FastTransforms.v0.2.13.i686-linux-musl-libgfortran4.tar.gz"
