[[FastTransforms]]
arch = "aarch64"
git-tree-sha1 = "7c7309843be3ddc180443e70d42d0b97382e5026"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "ae3e3b18be284c1d9930c4f44b7a0ab10bf816cd101d4e987e221d52274294eb"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.4.0+0/FastTransforms.v0.4.0.aarch64-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "aarch64"
git-tree-sha1 = "7d2f939825e4a46c8a0e8bab49b416db4110dadc"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "1cbd34e3220e50d762d4de523ba90cef6fd34c5aeeb18a2c095438f759eda9bd"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.4.0+0/FastTransforms.v0.4.0.aarch64-linux-musl.tar.gz"
[[FastTransforms]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3f209de94d82361cb756f0bd991dda4f3feefdb5"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "c4157e6e70f5b49a4682d2544a694decc89fa4a0725317a001ff85b8c3265888"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.4.0+0/FastTransforms.v0.4.0.armv7l-linux-gnueabihf.tar.gz"
[[FastTransforms]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ab12249197b37656f9a63e55f08ac712e84326cc"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "2d5d9050c800f5e7012532f8459433c214538b83546ec2560784576b6289c1ec"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.4.0+0/FastTransforms.v0.4.0.armv7l-linux-musleabihf.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "7dd0e9deb642949cb465d3fa51fbc24c6d306ee5"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "5cf396f8d7471b09c577feff11e37b1aeeadd2b9d9a8aa2fe88dbfc504140220"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.4.0+0/FastTransforms.v0.4.0.i686-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "b8253f3b4d14f03539c52111f05f3ecf00a7b36b"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "f187e665c9367a47f6cd54d985f944bbeb8626db8dba491c4ebf71993780080c"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.4.0+0/FastTransforms.v0.4.0.i686-linux-musl.tar.gz"
[[FastTransforms]]
arch = "i686"
git-tree-sha1 = "5f011592c58e8510a17fd1a2d4e9d32c2cc76317"
os = "windows"

    [[FastTransforms.download]]
    sha256 = "fbfe457030ca157ad5e876f01a952ee9235dd9999fa91acfccd631d69ccb26ac"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.4.0+0/FastTransforms.v0.4.0.i686-w64-mingw32.tar.gz"
[[FastTransforms]]
arch = "powerpc64le"
git-tree-sha1 = "4dfe6961d871846d5a1c9147f6aee0f996ea31a2"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "3ae39caee8bfaab28e4c2236bb1a833d71c144276c0b92e7bf85139192366cb3"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.4.0+0/FastTransforms.v0.4.0.powerpc64le-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "15fb637bd088b1f4ebbfceefbe72900946fb67ee"
os = "macos"

    [[FastTransforms.download]]
    sha256 = "bfeda3c210c14c8ff364427f516084ec9a3bdb6faf649f3aa0158e097c03cdc5"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.4.0+0/FastTransforms.v0.4.0.x86_64-apple-darwin.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "3fee1c0d34a5f0359de0f4aa9d0d23fb86a59be5"
libc = "glibc"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "91d73c37bf5956d1ed632a63b0a9c3938b6859ea3b5ae8e4f65eda5d1e98260c"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.4.0+0/FastTransforms.v0.4.0.x86_64-linux-gnu.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "ac80cafbcf7532e2a0bc6cb248d0bd9ded4bc369"
libc = "musl"
os = "linux"

    [[FastTransforms.download]]
    sha256 = "0ac7c3291487e834abbff65fa8d4ce8a47beac92789671196f7be9525809ca4d"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.4.0+0/FastTransforms.v0.4.0.x86_64-linux-musl.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "f50514002a9e1c6427f48f6c89ad4c32aaea24c1"
os = "freebsd"

    [[FastTransforms.download]]
    sha256 = "f3e6fac3aa64b0573fa1725c2ad3a81162c161eed14d364871d1515d0f3e6492"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.4.0+0/FastTransforms.v0.4.0.x86_64-unknown-freebsd.tar.gz"
[[FastTransforms]]
arch = "x86_64"
git-tree-sha1 = "b3c77c96cfae93d1d6de4eaf78e4bad8f06be36f"
os = "windows"

    [[FastTransforms.download]]
    sha256 = "cb4687092a5a877a61f934cadab1fdaf30fdc47316fff4177fb27e18d02cca41"
    url = "https://github.com/JuliaBinaryWrappers/FastTransforms_jll.jl/releases/download/FastTransforms-v0.4.0+0/FastTransforms.v0.4.0.x86_64-w64-mingw32.tar.gz"
